// POST ACTION TYPES ::
export const CREATE_POST_LOADING = "CREATE_POST_SUCCESS_LOADING";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const ALL_POST_LOADING = "ALL_POST_LOADING";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_ERROR = "ALL_POST_ERROR";

export const SINGLE_POST_LOADING = "SINGLE_POST_LOADING";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_ERROR = "SINGLE_POST_ERROR";

export const UPDATE_POST_LOADING = "UPDATE_POST_LOADING";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";

export const DELETE_POST_LOADING = "DELETE_POST_SUCCESS_LOADING";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
